### PR TITLE
WOLFMQTT_EXAMPLE_CERT allowing static or extern cert assignment

### PR DESCRIPTION
**Pull request by gojimmypi**
Related to https://github.com/wolfSSL/wolfMQTT/issues/352, this PR introduces the `WOLFMQTT_EXAMPLE_CERT` to allow the `CMakeLists.txt` in an Espressif Managed Component project to build the AWS example using the certs defined in [examples/aws/awsiot.c](https://github.com/wolfSSL/wolfMQTT/blob/28dffb5c03d4fb6a87a69f1115efefbcda8ef495/examples/aws/awsiot.c#L75)  and used in the [examples/mqttexample.c](https://github.com/wolfSSL/wolfMQTT/blob/28dffb5c03d4fb6a87a69f1115efefbcda8ef495/examples/mqttexample.c#L653) source.

## GitHub Workflow Update Included

edit: Thank you @bandi13 for the [.github/workflows/ubuntu-check.yml](https://github.com/wolfSSL/wolfMQTT/pull/354/commits/80bd582d0fdf030f7fcd9cdaa40905656b6dd145) update included here that helped identify the occasional workflow network failure, as well as the [workflow updates in #355](https://github.com/wolfSSL/wolfMQTT/pull/355/commits/2e31de09d2996c5b8ee3e2c7cc7223b42985c6f4). 

## Background

Without this change, included files outside of the project directory like this:

```
idf_component_register(SRCS
                       	    main.c
                       	    wifi_connect.c
                       	    time_helper.c
                       	    ${WOLFMQTT_ROOT}/examples/aws/awsiot.c
                       	    ${WOLFMQTT_ROOT}/examples/mqttexample.c
                       	    ${WOLFMQTT_ROOT}/examples/mqttnet.c
                       	    ${WOLFMQTT_ROOT}/examples/mqttport.c
                        INCLUDE_DIRS
                            "."
                            "./include"
                        )
```

... fail to properly build:

```
C:/workspace/wolfMQTT-gojimmypi/examples/mqttexample.c:662:30: error: 'device_cert' undeclared (first use in this function)
  662 |                 (const byte*)device_cert, (long)sizeof(device_cert),
```

The PR is an alternative to my current method of _copying_ those [files to the local project](https://github.com/gojimmypi/wolfMQTT/tree/d6f76c9f849544be2022e33abd76d69806b0ebda/IDE/Espressif/ESP-IDF/examples/AWS_IoT_MQTT/main/examples) directory. Although the copy works, it is one more point of maintenance when the example certs expire.

## Usage

Define `WOLFMQTT_EXTERN_CERT` either in `user_settings.h`, or in the case of Managed Component examples, this `cmake` line is added to the main project `CMakeLists.txt`:

```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DWOLFMQTT_EXTERN_CERT")
``` 

See also the [published wolfSSL Managed Component](https://components.espressif.com/components/wolfssl/wolfssl).

### CODE REVIEW

**Comment by gojimmypi** [comment]
retest this please

I checked this PR on Ubuntu,: installing wolfSSL and successfully doing a `make` for all the MQTT examples. I'm not sure why the tests failed with `Error: The operation was canceled.`

**Review by embhorn — APPROVED** [review]
Great!

**Review by embhorn — CHANGES_REQUESTED** [review]
Please fix the conflicts after I merged #355

**Comment by gojimmypi** [comment]
Jenkins retest this please.

**Review by embhorn — APPROVED** [review]

**Pull request merged**
