### PR TITLE
Fix link to arduino readme file

### PR DESCRIPTION
**Pull request by saloid**

### CODE REVIEW

**Comment by dgarske** [comment]
Hi saloid,

Thanks for finding this README typo!

In order to accept contributions we need to have a signed contributor agreement on file. Please email us at support@wolfssl.com and we'll provide you the document.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi @saloid : We are happy to review this contribution. Can you resolve the merge conflicts? Also please review my feedback in the previous comment. We cannot move files as it would break existing users.

Thanks,
David Garske, wolfSSL

**Comment by saloid** [comment]
Hello, sorry, last commit was for my own project. I have moved it to another branch and reverted in main - now should be ok.

**Comment by kaleb-himes** [comment]
Closing this out, requested changes were never made. Headers can not be moved. See also ZD 5542 for close-out.

**Pull request closed without merging**
