### PR TITLE
Fixes wm_Sem_t on Win32.

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by dgarske** [comment]
OK to test

**Comment by lygstate** [comment]
Can this be merged?

**Comment by dgarske** [comment]
> Can this be merged?

Due to the contributor agreement issues no, but we can treat this as a bug report and implement fixes ourselves based on testing. I will make sure we get this fixed.

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
@lygstate treating this as bug report and assigning task to @lealem47. Marking this PR closed.

**Comment by lygstate** [comment]
@dgarske What the issue with  contributor agreement ?

**Pull request closed without merging**
