### PR TITLE
Trim trailing spaec of mqtt_client.c mqttnet.c

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by dgarske** [comment]
OK to test

**Comment by lygstate** [comment]
no reason to fail, curious

**Comment by dgarske** [comment]
Looks like the `scripts/awsiot.test` test reported a failure. Retrying it, but could be something with the AWS server that caused an error. I agree no issue with the code.

**Comment by dgarske** [comment]
Will cover this cleanup in a new PR.

**Pull request closed without merging**
